# Конфигурация для подключения к базе данных
database:
  host: "192.168.0.100"
  user: "logger"
  password: "qn9@NiUYb"
  database: "keylogging"

# Настройки для работы с нейросетью
llm:
  prompt: |
    Ты проводишь анализ сентимента и эмоционального окраса текста. Перед тобой текст, разделенный по словам, проанализируй его указанным выше методом и предоставь вердикт, какое настроение было у человека в момент его написания. На выбор у тебя несколько вариантов:
    1. Хорошее
    2. Грустное
    3. Смешанное
    4. Злость
    5. Обида
    Сам текст:
    {word_data}
    Отвечай СТРОГО одним из этих вариантов, одним словом, и не пиши СОВСЕМ ничего кроме одного слова.
    Учитывай, что пользователь может допускать опечатки в словах